######### MEDIA SERVER APPS ##########

# Plex Media Server
  plexms:
    container_name: plexms
    hostname: plexms
    restart: always
    image: plexinc/pms-docker
    volumes:
      - /docker/plex:/config
      - /docker/plex/Downloads/plex_tmp:/transcode
      - /media/media:/media
      - /docker/plex/shared:/shared
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ=America/Denver
      - HOSTNAME="Docker Plex"
      - PLEX_CLAIM="claim-YYYYYYYYY"
      - PLEX_UID=1000
      - PLEX_GID=1000
      - ADVERTISE_IP="http://SERVER-IP:32400/"
      
######### DOCKER RELATED ##########

# Watchtower - Automatic Update of Containers/Apps
  watchtower:
    container_name: watchtower
    hostname: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup

# NZBGet – Usenet (NZB) Downloader (Alternative)
  nzbget:
    image: "linuxserver/nzbget"
    hostname: nzbget
    container_name: "nzbget"
    volumes:
      - /docker/sabnzbd:/config
      - /Downloads:/downloads
      - /Downloads/incomplete:/incomplete-downloads
      - /docker/shared:/shared
    ports:
      - "6789:6789"
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
